# Generated by Django 2.2.16 on 2022-11-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221111_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
